"""Add duration to appointment

Revision ID: 900ec8ca1cdd
Revises: e183a92ea10b
Create Date: 2026-01-31 10:57:16.921224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '900ec8ca1cdd'
down_revision = 'e183a92ea10b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duration', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.drop_column('duration')

    # ### end Alembic commands ###
